sudo: required

services:
  - docker

before_install:
  - apt-get install -y jq
  - docker pull gitlab/gitlab-ce:latest
  - |
    docker run --detach \
    --hostname gitlab.local \
    --publish 443:443 --publish 80:80 --publish 22:22 \
    --name gitlab \
    -e "GITLAB_ROOT_PASSWORD=thisisjustatest" \
    --restart always \
    --volume $(pwd)/.gitlab/config:/etc/gitlab \
    --volume $(pwd)/.gitlab/logs:/var/log/gitlab \
    --volume $(pwd)/.gitlab/data:/var/opt/gitlab \
    gitlab/gitlab-ce:latest
  - |
    until $(curl --output /dev/null --silent --head --fail http://localhost:80); do
        printf '.'
        sleep 5
    done
  - |
    export PRIVATE_TOKEN=$(curl http://localhost/api/v3/session/ --data-urlencode 'login=root' --data-urlencode 'password=thisisjustatest' | jq -r .private_token) && \
    curl --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" -X POST "http://localhost/api/v3/projects?name=foobartest"
